---
title: "p8105_hw5_sw3737"
author: "Shiqi Wu"
date: "2023-11-14"
output: github_document
---

```{r setup, include=FALSE}
library(purrr)
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
```

# Problem 1

## Creating a Dataframe and Binding the Data
```{r}
file_names <- list.files(path = "data", pattern = "*.csv", full.names = TRUE)

combined_data <- map_df(file_names, function(file_name) {
  data <- read_csv(file_name)
  
  data <- data %>%
    mutate(
      arm = ifelse(grepl("con", file_name), "control", "experimental"),
      subject_id = gsub(".*_(\\d+).csv", "\\1", basename(file_name))
    )

  return(data)
})
```

## Tidying the Data
```{r}
tidy_data <- combined_data %>%
  pivot_longer(
    cols = starts_with("week"), 
    names_to = "week", 
    values_to = "observation"
  )
```

## Creating a Spaghetti Plot
```{r}
ggplot(tidy_data, aes(x = week, y = observation, group = interaction(arm, subject_id), color = arm)) +
  geom_line() +
  scale_color_manual(values = c("control" = "pink", "experimental" = "lightblue")) +
  labs(title = "Observations Over Time by Subject",
       x = "Week",
       y = "Observation",
       color = "Group") +
  theme_minimal()
```

